version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  supervisor-agent:
    build: .
    image: jsoehner/spring-ai-agent:latest
    ports:
      - "8081:8080"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - SPRING_PROFILES_ACTIVE=supervisor
      - SPRING_RABBITMQ_HOST=rabbitmq
      - RESEARCHER_URL=http://researcher-agent:8080/research
      - IMAGE_AGENT_URL=http://image-agent:8080/image
      - SPRING_AI_OLLAMA_BASE_URL=http://192.168.100.190:11434
      - SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.ai.model.openai.autoconfigure.OpenAiChatAutoConfiguration
    depends_on:
      - rabbitmq
    volumes:
      - ./config:/app/config
      - ./.git:/app/.git
      - ./blog_draft.html:/app/blog_draft.html
      - ./blog_draft_wp.html:/app/blog_draft_wp.html

  researcher-agent:
    build: .
    image: jsoehner/spring-ai-agent:latest
    environment:
      - SPRING_PROFILES_ACTIVE=researcher
      - SPRING_RABBITMQ_HOST=rabbitmq
      - IMAGE_AGENT_URL=http://image-agent:8080/image
      - SPRING_AI_OLLAMA_BASE_URL=http://192.168.100.190:11434
      - SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.ai.model.openai.autoconfigure.OpenAiChatAutoConfiguration
    depends_on:
      - rabbitmq
    volumes:
      - ./config:/app/config
      - ./blog_draft.html:/app/blog_draft.html
      - ./blog_draft_wp.html:/app/blog_draft_wp.html

  image-agent:
    build: .
    image: jsoehner/spring-ai-agent:latest
    environment:
      - SPRING_PROFILES_ACTIVE=image-agent
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_AI_OLLAMA_BASE_URL=http://192.168.100.190:11434
      - SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.ai.model.openai.autoconfigure.OpenAiChatAutoConfiguration
    depends_on:
      - rabbitmq
    volumes:
      - ./config:/app/config

  opa:
    image: openpolicyagent/opa:latest-debug
    ports:
      - "8181:8181"
    command:
      - "run"
      - "--server"
      - "--log-level=debug"
      - "/policies"
    volumes:
      - ./security-policies/opa-guardrails/data/config.json:/policies/config.json
      - ./security-policies/opa-guardrails/policies:/policies/policies
