package com.example.demo.service;

import com.example.demo.agent.MarkdownSanitizer;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class MarkdownSanitizerTest {

    private final MarkdownSanitizer sanitizer = new MarkdownSanitizer();

    @Test
    void testNormalizesUserReportedSpacingAndLinefeeds() {
        String input = """
                <!-- wp: paragraph -->
                <p>Leadership ought to oversee a diverse array of technologies, including cloud computing, data management — and specialized firm apps that handle daily workloads for staff. Security gaps often exist between other platforms because they may not talk with one another well or share threat intelligence automatically between teams. Addressing these vulnerabilities requires consistent auditing processes to maintain trust in digital services provided to clients and employees alike.</p>
                <!-- /wp: paragraph -->

                <!-- wp: heading -->
                <h4>Securing Infrastructure and Strategic Summary</h4>
                <!-- /wp: heading -->
                """;

        String expected = """
                <!-- wp:paragraph --><p>Leadership ought to oversee a diverse array of technologies, including cloud computing, data management — and specialized firm apps that handle daily workloads for staff. Security gaps often exist between other platforms because they may not talk with one another well or share threat intelligence automatically between teams. Addressing these vulnerabilities requires consistent auditing processes to maintain trust in digital services provided to clients and employees alike.</p><!-- /wp:paragraph -->
                <!-- wp:heading --><h4>Securing Infrastructure and Strategic Summary</h4><!-- /wp:heading -->""";

        String actual = sanitizer.process(input);
        assertEquals(expected, actual);
    }

    @Test
    void testStripsMarkdownFencesAndCleansCarriageReturns() {
        String input = "```html\r\n<!-- wp:heading -->\r\n<h2>Title</h2>\r\n<!-- /wp:heading -->\r\n\r\n<!-- wp:paragraph -->\r\n<p>Content line</p>\r\n<!-- /wp:paragraph -->\r\n```";

        String expected = "<!-- wp:heading --><h2>Title</h2><!-- /wp:heading -->\n<!-- wp:paragraph --><p>Content line</p><!-- /wp:paragraph -->";

        String actual = sanitizer.process(input);
        assertEquals(expected, actual);
    }

    @Test
    void testNormalizesTagNamesWithExtraSpaces() {
        String input = "<!--   wp:   paragraph   -->\n<p>Test</p>\n<!--   /wp:   paragraph   -->";
        String expected = "<!-- wp:paragraph --><p>Test</p><!-- /wp:paragraph -->";

        String actual = sanitizer.process(input);
        assertEquals(expected, actual);
    }

    @Test
    void testNormalizesImageBlocksAndRemovesExtraBlankLines() {
        String input = """
                <!-- wp:image -->
                <figure class="wp-block-image">
                    <img src="http://example.com/pic.png" alt="Pic"/>
                </figure>
                <!-- /wp:image -->


                <!-- SEO: Generated by BlogAgent -->
                <meta name="description" content="Automated security blog post.">

                <!-- wp:heading -->
                <h2>Main Title</h2>
                <!-- /wp:heading -->

                <!-- wp:paragraph -->
                <p>
                    Paragraph line 1.
                    Paragraph line 2.
                </p>
                <!-- /wp:paragraph -->
                """;

        String expected = """
                <!-- wp:image --><figure class="wp-block-image"><img src="http://example.com/pic.png" alt="Pic"/></figure><!-- /wp:image -->
                <!-- wp:heading --><h2>Main Title</h2><!-- /wp:heading -->
                <!-- wp:paragraph --><p>Paragraph line 1. Paragraph line 2.</p><!-- /wp:paragraph -->""";

        String actual = sanitizer.process(input);
        assertEquals(expected, actual);
    }

    @Test
    void testAutoHealsMissingHtmlTagsInHeadingAndParagraphBlocks() {
        String input = """
                <!-- wp:heading -->The Dual-Use Reality of Generative Models<!-- /wp:heading -->
                <!-- wp:paragraph -->The cybersecurity landscape currently faces a fundamental paradox.<!-- /wp:paragraph -->
                """;

        String expected = """
                <!-- wp:heading --><h2>The Dual-Use Reality of Generative Models</h2><!-- /wp:heading -->
                <!-- wp:paragraph --><p>The cybersecurity landscape currently faces a fundamental paradox.</p><!-- /wp:paragraph -->""";

        String actual = sanitizer.process(input);
        assertEquals(expected, actual);
    }

    @Test
    void testStripsDangerousElements() {
        String input = """
                <!-- wp:paragraph -->
                <p>Normal text.</p>
                <script>alert('xss')</script>
                <iframe src="https://evil.com"></iframe>
                <object data="evil.swf">payload</object>
                <embed src="evil.swf">
                <applet code="evil.class"></applet>
                <style>body { display: none; }</style>
                <svg onload="alert('svg-xss')"><circle r="10"/></svg>
                <!-- /wp:paragraph -->
                """;

        String result = sanitizer.process(input);
        org.junit.jupiter.api.Assertions.assertFalse(result.contains("<script"));
        org.junit.jupiter.api.Assertions.assertFalse(result.contains("<iframe"));
        org.junit.jupiter.api.Assertions.assertFalse(result.contains("<object"));
        org.junit.jupiter.api.Assertions.assertFalse(result.contains("<embed"));
        org.junit.jupiter.api.Assertions.assertFalse(result.contains("<applet"));
        org.junit.jupiter.api.Assertions.assertFalse(result.contains("<style"));
        org.junit.jupiter.api.Assertions.assertFalse(result.contains("<svg"));
        org.junit.jupiter.api.Assertions.assertTrue(result.contains("<p>Normal text.</p>"));
    }

    @Test
    void testStripsInlineDomEventHandlers() {
        String input = """
                <!-- wp:paragraph -->
                <p onclick="alert('p-click')" onmouseover="steal()">Safe paragraph content</p>
                <img src="http://example.com/pic.png" onload="alert('loaded')" onerror="alert('error')" alt="Photo"/>
                <!-- /wp:paragraph -->
                """;

        String result = sanitizer.process(input);
        org.junit.jupiter.api.Assertions.assertFalse(result.contains("onclick"));
        org.junit.jupiter.api.Assertions.assertFalse(result.contains("onmouseover"));
        org.junit.jupiter.api.Assertions.assertFalse(result.contains("onload"));
        org.junit.jupiter.api.Assertions.assertFalse(result.contains("onerror"));
        org.junit.jupiter.api.Assertions.assertTrue(result.contains("<p>Safe paragraph content</p>"));
        org.junit.jupiter.api.Assertions.assertTrue(result.contains("src=\"http://example.com/pic.png\""));
    }

    @Test
    void testStripsJavascriptAndVbscriptUris() {
        String input = """
                <!-- wp:paragraph -->
                <p><a href="javascript:alert('xss')">Malicious Link</a></p>
                <p><a href="vbscript:msgbox('xss')">VB Link</a></p>
                <img src="javascript:alert('img')" alt="Malicious Img"/>
                <!-- /wp:paragraph -->
                """;

        String result = sanitizer.process(input);
        org.junit.jupiter.api.Assertions.assertFalse(result.contains("javascript:"));
        org.junit.jupiter.api.Assertions.assertFalse(result.contains("vbscript:"));
        org.junit.jupiter.api.Assertions.assertTrue(result.contains("Malicious Link"));
        org.junit.jupiter.api.Assertions.assertTrue(result.contains("VB Link"));
    }
}
