package com.example.demo.service;

public class SeoMetadataInjector implements ContentProcessor {
    @Override
    public String process(String content) {
        if (content == null) return null;
        
        // Inject some default SEO meta tags or classes
        String meta = "\n<!-- SEO: Generated by BlogAgent -->\n<meta name=\"description\" content=\"Automated security blog post.\">";
        return meta + content;
    }
}
